### ISSUE TITLE
RightClickTools.zip identifying as Malware

### ISSUE THREAD

**Issue by Simon-Bell** [LesFerch/RightClickTools#2]
Downloaded RightClickTools.zip. 
SHA-1    777253B294C4BBC8290C9CBF8DA37A211F0C91C41A32F0D490B360E420E90159
Emisoft identified Gen:Variant.Jalapeno.5755
VirusTotal  14 of 69 identified a Trojan by various names.

**Comment by LesFerch** [comment]
Those are false positives.

You're going to see that with Windows utilities, especially from small developers and individual contributors, such as myself. Right-Click Tools creates a scheduled task that's used to provide elevated privileges, so it's going to look suspicious to a lot of anti-malware products.

AV vendors have to use heuristics to determine if something "looks" like it could be malware. Obviously, utilities that write to the registry and set up scheduled tasks will fall into that category. The AV vendors can't limit their flagging to exact matches of known malware because then the malware creators would only have to make the most trivial change to avoid detection. Therefore, legitimate software gets caught in the net all the time.

VirusTotal will continue to throw up these false positives no matter what, but if Windows Defender throws up a false detection, I will report it to the Windows Defender team. They are very responsive in making the appropriate corrections to their definitions. I can't chase down the plethora of other AV vendors.

Common sense should tell you that Right-Click Tools is safe as long as you're getting it from a reputable site (I recommend getting it straight from GitHub). Consider that it's open source, the exe is signed, my personal email is posted, it has a growing number of stars on GitHub, and has been downloaded a lot already. If it contained malware, I'd be kicked off of GitHub in a heartbeat.

For more perspective, please see these pages from a couple of free software developers:

http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/

https://ritchielawrence.github.io/cmdow/#is-cmdow-malware

**Comment by Simon-Bell** [comment]
Wow! Extensive and extremely rapid reply. Thank-you! Yes, you had mentioned Right-Click Tools had received positives in the past. I was just reporting on the current state of affairs. Yes both MS-Defender and Malwarebytes passed for me. 
  Common sense should tell anybody to be wary of software identified as malware, increasingly so, as the number of reports become significant. The sense that is common, however, well.. how could malware survive, with out it ?
   It's truly unfortunate, for all, that it takes so much effort on your part, to submit a file and get it successfully whitelisted.  Your utility looks to be amazing.  Sincerely thank you, for sharing your talent and efforts with others.

**Comment by LesFerch** [comment]
You're very welcome! 🙂

As I find time, I will try to submit the app to other vendors, although, given its nature, it could be challenging to get a green light. In the past, I submitted WinSetView to Kaspersky and that went well and resolved a false positive. That was a couple of years ago and WinSetView doesn't look as suspicious to AV software as Right-Click Tools, so... we'll see.

I am currently working on Right-Click Tools 1.1. The big new feature is "Privileged file manager here" which will launch Explorer (or the file manager of your choosing) as Administrator or Trusted Installer. I hope to post that sometime in the next few days.
