### ISSUE TITLE
New version 1.1.0 not working, previous version was ok.

### ISSUE THREAD

**Issue by meatwar** [LesFerch/RightClickTools#3]
Attaching event viewer files from W11 23H2 (22631.4317)

Nice util and thank you.

[RCtool_W_events.zip](https://github.com/user-attachments/files/17340943/RCtool_W_events.zip)

**Comment by LesFerch** [comment]
Is it failing to install or failing when you select one of the tools?

I can see a "System.InvalidOperationException" error in the XML file, but no clue as to where that's happening in the code. The file `Windows Error Reporting.xml` refers to a bunch of other files in `C:\ProgramData\Microsoft\Windows\WER\Temp`. Maybe there's more details there. Could you zip those up and post them?

**Comment by meatwar** [comment]
I use only portable ones, no failures running the app 1.0.3 or 1.1.0, everything seems ok, task is created, but tool not visible/created in regular or classic W11 right click.
There's 5 files on C:\ProgramData\Microsoft\Windows\WER\Temp, none have data related to RightClickTools and older dates/hours prior to the tryouts of Sting up your utility.
Im suspecting its something related to WU or .NET updates, cause version 1.0.3 was running ok 1 or 2 weeks ago since i installed, many thanks for your time.

**Comment by LesFerch** [comment]
Thanks for the info. I tested with 23H2 22631.4317 with language set to Spanish. No problems observed. Initial launch of tools has small delays (especially Run as Trusted Installer), but that's normal for first run of .Net apps. Version 1.1.0 is built from the same project as 1.0.3, with all Visual Studio settings the same, the .Net target still set to 4.8, and all the same `using` directives, so it's really strange that 1.0.3 works on your computer but not 1.1.0. I did add a `[STAThread]` statement to 1.1.0 because all the documentation and advice online says that I should do that if there are any GUI elements (e.g. dialogs) although I'm still not convinced it's needed for simple message boxes. I could compile a copy without that statement for you to try, but I think it's unlikely to make any difference.

Have you tried with a different local user account just in case there's something about your profile that's making it fail?

Also, do you have any other computers or VMs you can test it on?

**Comment by meatwar** [comment]
Portuguese here. Only one user local account admin on my main system.
Just tested now on a new client side build system, W11 24H2. 
No dice... and this is a new, clean system not yet delivered to the client.

**Comment by LesFerch** [comment]
OK. Portuguese Brazil or Portugal? Any third-party AV software installed?

**Comment by meatwar** [comment]
My dotnetver.exe is the same as yours...
This is from my system, the other was from the new build client.
![image](https://github.com/user-attachments/assets/f76feec9-239e-4832-b75c-8671393d2bcf)

<32Bit>
2.0.50727.9179
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.8.9277.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.9179
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.8.9277.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

==== Installed .NET Frameworks ====
.NET FW 2.0 SP 2 (CLR 2.0)
.NET FW 3.0 SP 2 (CLR 2.0)
.NET FW 3.5 SP 1 (CLR 2.0)
.NET FW 4.6.2 Windows 11 22H2(CLR 4.0)
.NET FW 4.7 Windows 11 22H2(CLR 4.0)
.NET FW 4.7.1 Windows 11 22H2(CLR 4.0)
.NET FW 4.7.2 Windows 11 22H2(CLR 4.0)
.NET FW 4.8 Windows 11 22H2(CLR 4.0)
.NET FW 4.8.1 Windows 11 22H2(CLR 4.0)

==== Languages ====
< Installed Languages 3.0>
English - United States
Portuguese – Portugal
< Installed Languages 3.5.x>
English - United States
Portuguese – Portugal
< Installed Languages 4.x>
English - United States
Portuguese – Portugal

==== Updates ====
Microsoft .NET Framework 4 Client Profile 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Extended 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217

**Comment by LesFerch** [comment]
When I run `dotnetver.exe` on my Windows 10 host, the report looks the same as yours. Maybe the difference with my Windows 11 report is due to it running in VMWare. Maybe those differences are a non-issue.

I saw the (G) after your language code and thought that might mean Galego, so I set my Windows 11 to that language to see what would happen. I don't have that language in my `Language.ini file`, so it should create the menu entries in English, which it did with one glitch, but it still worked fine and there were no errors in the event viewer.

![image](https://github.com/user-attachments/assets/a395a9cf-1437-4498-b437-0eca2f573a29)

I'm going to try a fresh Windows 11 build. Please let me know all settings that you change from the default (e.g. exact language chosen, regional settings, etc.).

**Comment by LesFerch** [comment]
I just posted 1.1.1 which fixes that bug when there is no matching language in the Language.ini file. I doubt that it will make any difference to what you're seeing, but it couldn't hurt to try.

**Comment by LesFerch** [comment]
I just don't understand how 1.0.3 works. The menu entries are created with the same code. That bug that I just fixed was also present in 1.0.3. Maybe it's not my code, but some subtle change with .Net. It works for me with the same OS build, so the question is what's different. Anything you can tell me about your build that could differ from mine may be helpful.

**Comment by meatwar** [comment]
Me neither... but all i see is errors related to .NET
Yes i'm starting to think that this has nothing to do with your code...anything related to Windows and recent updates, as the 1.0.3 never worked again, also after recent updates, as i told you before. Stay put for now... this is starting to look as an isolated case or its related to MS OS/.NET

**Comment by LesFerch** [comment]
Sorry, I misread earlier. Good to know that 1.0.3. is also no longer working. That makes more sense. I'm doing a fresh Windows 11 build to see if I can replicate the issue. I haven't had any other reports, so fingers crossed for me that it's something specific to your builds.

**Comment by meatwar** [comment]
Good news... i used setup instead of portable, yesterday before shutdown the sys, today's reboot i got the menu back on "More options" context, not in primary context, running the app i didn't selected "Classic", is this correct?
Side question, i see it applies to "Folder" and "Drive", what about "Take ownership" and "Run as Admin" for example to a file, is this missing or just wasn't implemented?

**Comment by LesFerch** [comment]
Just to clarify, menu items are only created in the new context menu if you have [Custom Context Menu](https://apps.microsoft.com/detail/9pc7bzz28g0x?hl=en-US&gl=US) installed. Is that installed?

Yes, by design there are no file functions. Run as Administrator is already provided by the OS in both old and new context menus and I think it's extremely rare to need to change ownership for an individual file versus the folder where it resides. I've never had to do that.

Does double-clicking RightClickTools.exe, and selecting "Remove", remove the menu items from the classic context menu? And does selecting "Install" add them back?

**Comment by meatwar** [comment]
Oh, no i haven't that installed...and its payed.

"Does double-clicking RightClickTools.exe, and selecting "Remove", remove the menu items from the classic context menu? And does selecting "Install" add them back?"
Yes, everything works as intended, thank you.

**Comment by LesFerch** [comment]
So, was there ever an issue or was this all a misunderstanding?

Also, Custom Context Menu can be used for free. It has an unlimited free trial.

**Comment by meatwar** [comment]
"So, was there ever an issue or was this all a misunderstanding?"
Really cant figure it out... maybe the OS itself since it was never cleaned installed since W11 came out and always was upgraded on top and hw platform changed to Z490 in spring, will test on 2 more systems, but we can close it for now.
Kind regards, all the best.
